---
# basics parameters
app:
  name: "OpenGDC"                                             # App name
# Genomic Data Commons API coordinates
gdc:
  searchurl: "https://api.gdc.cancer.gov/files"               # GDC files endpoint
  downloadurl: "https://api.gdc.cancer.gov/data/"             # GDC data endpoint
  size: 10000                                                 # Query size limit
  repeat: 5                                                   # Max number of connection attempts if GDC is not reachable
# assets parameters
assets:
  gencode: "./assets/gencode.v22.annotation.gtf.bz2"          # GENCODE Annotations V22
  ncbi: 
    history: "./assets/gene_history.txt.bz2"                  # NCBI Deprecated Genese
    reference: "./assets/ref_GRCh38.p2_top_level.gff3.bz2"    # NCBI Genes Annotations GRCh38
  hgnc: "./assets/hgnc_complete_set.txt.bz2"                  # HUGO Gene Nomenclature Committee Annotations
...